### PR TITLE
added travis configuration file

### PR DESCRIPTION
**Pull request by hrj**
This will enable automatic builds in travis-ci.org.

### CODE REVIEW

**Comment by darkfrog26** [comment]
Because of the same reasons you were having problems getting your environment set up, we would have problems with Travis.  Hyperscala currently relies on snapshots for powerscala and outrnet so it is incredibly likely builds will fail frequently on Travis.  I have a Jenkins server, but I need to get it re-configured to work properly so we can have dependent builds.

**Comment by hrj** [comment]
Yeah, I realize that it will fail as of now; but couldn't you enable it and publish the snapshots frequently? The idea is to reach a stable state faster.

**Comment by darkfrog26** [comment]
Like I said, I have a Jenkins server that allows me to support dependent builds...why would I want Travis?

**Comment by hrj** [comment]
Oh; I am not particular about Travis. Even Jenkins is fine if somebody else is doing the configuration :) I found Jenkins powerful but messy to configure.

In any case, travis might be a quicker alternative in the short term. It requires zero configuration beyond this PR. Though it will require snapshots being published at regular intervals for the builds to pass.

Is the publishing of snapshots cumbersome? (I have no experience in that area).

Aside; I was hoping to setup https://coveralls.io/ too. It was pretty easy to setup along with travis-ci in [one of my projects](https://github.com/hrj/abandon). It will probably work with  Jenkins as well; I didn't try that combination yet.

**Comment by darkfrog26** [comment]
There are SBT plugins that provide the majority of that and can be generated as part of the Jenkins build.  Don't worry about this stuff, just focus on going through the code right now.

**Pull request closed without merging**
